### ISSUE TITLE
It's possible to score points by clicking on dead cows

### ISSUE THREAD

**Issue by tttppp** [nyoany/games#2]
There seems to be code to prevent this, but when I tested it wasn't behaving as expected. Clicking on a dead cow moves it back to the top and scores some points.

The cow doesn't move once it's at the top of the screen, but this doesn't seem like the desired behaviour.

**Comment by nyoany** [comment]
Fixed with https://github.com/nyoany/games/commit/447b106d0cc0e23da5c06c85508da8a194345e1c.
