### ISSUE TITLE
Cows saved multiplier

### ISSUE THREAD

**Issue by tttppp** [nyoany/games#3]
It would be good to reward players for saving all the cows by implementing a cows saved multiplier. If a user saves n cows then their score is multiplied by n.

If a user lets all the cows die then we should either give them 0 score, or just let them score whatever they managed by that point.

**Comment by nyoany** [comment]
Done as part of commit https://github.com/nyoany/games/commit/20d9d07953b0ff4d5a69087d99f3693ca3834145.

**Comment by tttppp** [comment]
Wow - all issues closed! We need some new ideas.
